server:
  port: 8080
  servLet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://ckqsczspljrojf:6fecf9f580921e59a1c0ff5a659b2b07447e636d35a69270c0622af965f47622@ec2-184-73-198-174.compute-1.amazonaws.com:5432/dbrdu1im24ms1d
    username: ckqsczspljrojf
    password: 6fecf9f580921e59a1c0ff5a659b2b07447e636d35a69270c0622af965f47622
  jpa:
    show-sql: true
    database-plataform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander